[boris]
  version = 1

[build.dist-7-10-core]
  command = [["master", "build", "dist-7-10", "-C", "machinator-core"]]

[build.dist-7-10-haskell]
  command = [["master", "build", "dist-7-10", "-C", "machinator-haskell"]]

[build.dist-7-10-purescript]
  command = [["master", "build", "dist-7-10", "-C", "machinator-purescript"]]

[build.branches-7-10-core]
  command = [["master", "build", "branches-7-10", "-C", "machinator-core"]]

[build.branches-7-10-haskell]
  command = [["master", "build", "branches-7-10", "-C", "machinator-haskell"]]

[build.branches-7-10-purescript]
  command = [["master", "build", "branches-7-10", "-C", "machinator-purescript"]]

[build.dist-validate]
  command = [["validate-respect"]]

[build.all-submodules]
  command = [["dangling-refs"]]

[build.all-rebased]
  command = [["rebased"]]

